#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

git secret hide -m && git add .gitsecret/paths/mapping.cfg && git add *.secret
git secret hide -m && git add .gitsecret/paths/mapping.cfg && git add *.secret
